"""add external_ref to work_orders

Revision ID: 786b9f3b2554
Revises: 76d5ee76edf6
Create Date: 2026-07-25 15:35:49.511162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '786b9f3b2554'
down_revision: Union[str, Sequence[str], None] = '76d5ee76edf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('external_ref', sa.String(), nullable=True))
    op.create_index(op.f('ix_work_orders_external_ref'), 'work_orders', ['external_ref'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_external_ref'), table_name='work_orders')
    op.drop_column('work_orders', 'external_ref')
    # ### end Alembic commands ###
