"""
Seed script for Phase 1.

Run once against a fresh database:
    python seed.py

Loads:
  - assets: from name_to_branch.json + name_to_camp_letter.json
            (already generated by parse_asset_hierarchy.py from
            Asset_Hierarchy_Analysis.md — point the paths below at your copy)
  - teams:  a starter list matching the team names already seen in the
            current Fiix export data; edit/extend as needed
  - one initial admin user (email/password printed at the end — change
    the password immediately after first login)

NOTE: this script assumes the schema already exists. Run migrations first:
    alembic upgrade head
    python seed.py
"""
import json
import os
import secrets
import sys

from sqlalchemy import inspect

from app.database import SessionLocal, engine
from app import models
from app.auth import hash_password

NAME_TO_BRANCH_PATH = os.environ.get("NAME_TO_BRANCH_PATH", "/mnt/project/name_to_branch.json")
NAME_TO_CAMP_LETTER_PATH = os.environ.get("NAME_TO_CAMP_LETTER_PATH", "/mnt/project/name_to_camp_letter.json")

STARTER_TEAMS = [
    "2026 Jamboree LOC (Work Order Management)",
    "2026 Jamboree Maintenance (Repairs and General Needs)",
    "2026 Jamboree IT",
    "2026 Jamboree ALC (Warehouse for Items)",
    "2026 Jamboree Allied (Contractor)",
    "2026 Jamboree Freeman (Contractor)",
]


def seed_assets(db):
    with open(NAME_TO_BRANCH_PATH) as f:
        name_to_branch = json.load(f)
    with open(NAME_TO_CAMP_LETTER_PATH) as f:
        name_to_camp_letter = json.load(f)

    existing = {a.name for a in db.query(models.Asset.name).all()}
    added = 0
    for name, branch in name_to_branch.items():
        if name in existing:
            continue
        db.add(models.Asset(
            name=name,
            location_group=branch,
            camp_letter=name_to_camp_letter.get(name),
        ))
        added += 1
    db.commit()
    print(f"assets: added {added}, {len(name_to_branch)} total in source")


def seed_teams(db):
    existing = {t.name for t in db.query(models.Team.name).all()}
    added = 0
    for name in STARTER_TEAMS:
        if name in existing:
            continue
        db.add(models.Team(name=name))
        added += 1
    db.commit()
    print(f"teams: added {added}")


def seed_admin(db):
    if db.query(models.User).filter(models.User.role == "admin").first():
        print("admin user already exists, skipping")
        return
    password = secrets.token_urlsafe(12)
    admin = models.User(
        name="LOC Admin",
        email="admin@njloc.local",
        password_hash=hash_password(password),
        role="admin",
    )
    db.add(admin)
    db.commit()
    print(f"admin user created: admin@njloc.local / {password}  (change this immediately)")


if __name__ == "__main__":
    if not inspect(engine).has_table("work_orders"):
        sys.exit(
            "Schema not found. Run `alembic upgrade head` before seeding "
            "(see README)."
        )
    db = SessionLocal()
    try:
        seed_assets(db)
        seed_teams(db)
        seed_admin(db)
    finally:
        db.close()
